<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pakaian extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pakaian_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));

        if ($q <> '') {
            $config['base_url'] = base_url() . 'pakaian/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'pakaian/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'pakaian/index.html';
            $config['first_url'] = base_url() . 'pakaian/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Pakaian_model->total_rows($q);
        $pakaian = $this->Pakaian_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'pakaian_data' => $pakaian,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->template->load('template','pakaian/pakaian_list', $data);
    }

    public function read($id)
    {
        $row = $this->Pakaian_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_pakaian' => $row->id_pakaian,
		'nama_pakaian' => $row->nama_pakaian,
	    );
            $this->template->load('template','pakaian/pakaian_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pakaian'));
        }
    }

    public function create()
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('pakaian/create_action'),
	    'id_pakaian' => set_value('id_pakaian'),
	    'nama_pakaian' => set_value('nama_pakaian'),
	);
        $this->template->load('template','pakaian/pakaian_form', $data);
    }

    public function create_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_pakaian' => $this->input->post('nama_pakaian',TRUE),
	    );

            $this->Pakaian_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('pakaian'));
        }
    }

    public function update($id)
    {
        $row = $this->Pakaian_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('pakaian/update_action'),
		'id_pakaian' => set_value('id_pakaian', $row->id_pakaian),
		'nama_pakaian' => set_value('nama_pakaian', $row->nama_pakaian),
	    );
            $this->template->load('template','pakaian/pakaian_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pakaian'));
        }
    }

    public function update_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_pakaian', TRUE));
        } else {
            $data = array(
		'nama_pakaian' => $this->input->post('nama_pakaian',TRUE),
	    );

            $this->Pakaian_model->update($this->input->post('id_pakaian', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('pakaian'));
        }
    }

    public function delete($id)
    {
        $row = $this->Pakaian_model->get_by_id($id);

        if ($row) {
            $this->Pakaian_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('pakaian'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pakaian'));
        }
    }

    public function _rules()
    {
	$this->form_validation->set_rules('nama_pakaian', 'nama pakaian', 'trim|required');

	$this->form_validation->set_rules('id_pakaian', 'id_pakaian', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Pakaian.php */
/* Location: ./application/controllers/Pakaian.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-09 06:40:40 */
/* http://harviacode.com */